# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  slack: circleci/slack@4.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "0e:9c:c6:ba:87:19:aa:fa:cb:dc:10:1f:e6:48:a3:2e"          
      - run:
          name: script
          command: |
            bash autotag.sh
