# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  slack: circleci/slack@4.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "89:b4:7f:9b:a0:47:02:c6:7d:06:86:80:ea:86:f7:06"          
      - run:
          name: script
          command: |
            bash autotag.sh
